[package]
name = "slide-thu"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Jez (https://github.com/Jzzzi)"]
license = "MIT-0"
description = "A slide template for Tsinghua University."
repository = "https://github.com/Jzzzi/slide-thu"
keywords = ["slides", "presentation", "beamer", "quarto"]
categories = ["presentation"]
compiler = "0.13.1"
exclude = ["screenshots", "example", "diaquarto"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "screenshots/Thumbnail.png"
